kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: fullduplexuk/voip-error-capturing
    tags: latest
